

name: CI Workflow

on:
  push:
    branches:
      - develop
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run:  develop branch is up

      